package com.geraj.assignment.dao;

import com.geraj.assignment.model.Account;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Objects;
import java.util.Optional;
import org.sqlite.SQLiteErrorCode;
import org.sqlite.SQLiteException;

/**
 * Stores and retrieves accounts using SQLite.
 */
public class SqliteAccountDAO implements IAccountDAO {
    private final Connection connection;

    /**
     * Creates an account DAO using the application's shared database connection.
     */
    public SqliteAccountDAO() {
        this(SqliteConnection.getInstance());
    }

    /**
     * Creates an account DAO using a supplied database connection.
     *
     * @param connection the connection used for account persistence
     */
    public SqliteAccountDAO(Connection connection) {
        this.connection = Objects.requireNonNull(
                connection,
                "Account database connection cannot be null"
        );
        createTable();
    }

    private void createTable() {
        String query = """
            CREATE TABLE IF NOT EXISTS accounts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL UNIQUE,
                email TEXT NOT NULL UNIQUE,
                firstName TEXT NOT NULL,
                lastName TEXT NOT NULL,
                phoneNumber TEXT NOT NULL,
                hash TEXT NOT NULL
            );
            """;

        try (Statement statement = connection.createStatement()) {
            statement.execute(query);
        } catch (SQLException exception) {
            throw new IllegalStateException(
                    "Could not create the accounts table",
                    exception
            );
        }
    }
    /**
     * Stores a new account and assigns its generated database identifier
     * to the supplied object.
     *
     * @param account the account to store
     * @throws IllegalStateException if insertion fails or no identifier is returned
     */
    @Override
    public void createAccount(Account account) {
        String query = """
        INSERT INTO accounts (name, email, firstName, lastName, phoneNumber, hash)
        VALUES (?, ?, ?, ?, ?, ?)
        """;

        // Request the identifier generated by SQLite for this insertion.
        try (PreparedStatement statement = connection.prepareStatement(
                query, Statement.RETURN_GENERATED_KEYS
        )) {
            statement.setString(1, account.getName());
            statement.setString(2, account.getEmail());
            statement.setString(3, account.getFirstName());
            statement.setString(4, account.getLastName());
            statement.setString(5, account.getPhoneNumber());
            statement.setString(6, account.getHash());
            statement.executeUpdate();

            try (ResultSet generatedKeys = statement.getGeneratedKeys()) {
                if (!generatedKeys.next()) {
                    throw new IllegalStateException(
                            "The account was created but no database identifier was returned"
                    );
                }

                // Preserve the generated identity on the caller's original object.
                account.setId(generatedKeys.getInt(1));
            }
        } catch (SQLException exception) {
            // Translate only an email uniqueness violation into an email conflict.
            // Other database failures retain their existing error handling.
            if (exception instanceof SQLiteException sqliteException
                    && sqliteException.getResultCode()
                    == SQLiteErrorCode.SQLITE_CONSTRAINT_UNIQUE
                    && sqliteException.getMessage() != null
                    && sqliteException.getMessage().contains(
                    "UNIQUE constraint failed: accounts.email"
            )) {
                throw new DuplicateAccountException("email", exception);
            }

            throw new IllegalStateException(
                    "Could not create the account", exception
            );
        }
    }

    /**
     * Finds an account by its username.
     *
     * @param searchName the username to find
     * @return the matching account, or null when no account exists
     */
    @Override
    public Account getAccountByName(String searchName) {
        String query = """
            SELECT id, name, email, firstName, lastName, phoneNumber, hash
            FROM accounts
            WHERE name = ?
            """;

        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, searchName);

            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return mapAccount(resultSet);
                }
            }
        } catch (SQLException exception) {
            throw new IllegalStateException("Could not find the account", exception);
        }

        return null;
    }

    /**
     * Finds an account by its database identifier.
     *
     * @param accountId the account identifier
     * @return the matching account, or an empty optional when none exists
     */
    @Override
    public Optional<Account> getAccountById(int accountId) {
        String query = """
            SELECT id, name, email, firstName, lastName, phoneNumber, hash
            FROM accounts
            WHERE id = ?
            """;

        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setInt(1, accountId);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return Optional.of(mapAccount(resultSet));
                }
            }
        } catch (SQLException exception) {
            throw new IllegalStateException("Could not find the account", exception);
        }

        return Optional.empty();
    }

    /**
     * Finds an account by its email address.
     *
     * @param email the email address to find
     * @return the matching account, or an empty optional when none exists
     */
    @Override
    public Optional<Account> getAccountByEmail(String email) {
        String query = """
            SELECT id, name, email, firstName, lastName, phoneNumber, hash
            FROM accounts
            WHERE email = ?
            """;

        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, email);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    return Optional.of(mapAccount(resultSet));
                }
            }
        } catch (SQLException exception) {
            throw new IllegalStateException("Could not find the account", exception);
        }

        return Optional.empty();
    }

    /**
     * Updates the editable personal information for an existing account.
     *
     * @param account the account containing the new personal information
     * @return true when one account was updated, otherwise false
     */
    @Override
    public boolean updatePersonalInformation(Account account) {
        String query = """
            UPDATE accounts
            SET firstName = ?, lastName = ?, email = ?, phoneNumber = ?
            WHERE name = ?
            """;

        try (PreparedStatement statement = connection.prepareStatement(query)) {
            statement.setString(1, account.getFirstName());
            statement.setString(2, account.getLastName());
            statement.setString(3, account.getEmail());
            statement.setString(4, account.getPhoneNumber());
            statement.setString(5, account.getName());
            return statement.executeUpdate() == 1;
        } catch (SQLException exception) {
            return false;
        }
    }

    /**
     * Converts the current database row into an account, preserving its identity.
     *
     * @param resultSet the query result positioned at the account row
     * @return the account containing its stored ID and account information
     * @throws SQLException if a required column cannot be read
     */
    private Account mapAccount(ResultSet resultSet) throws SQLException {
        Account account = new Account(
                resultSet.getString("name"),
                resultSet.getString("email"),
                resultSet.getString("firstName"),
                resultSet.getString("lastName"),
                resultSet.getString("phoneNumber"),
                resultSet.getString("hash")
        );

        // Restore the existing database identity without changing the constructor.
        account.setId(resultSet.getInt("id"));
        return account;
    }
}
